from utils import remove_macro_tags

text = """[vc_row][vc_column][vc_empty_space][mk_image src=&#8221;https://www.icelandreview.com/wp-content/uploads/2019/06/motmli011.jpg&#8221; image_size=&#8221;full&#8221; lightbox=&#8221;true&#8221; title=&#8221;Protesters in downtown Reykjavík during the Pots and Pans Revolution.&#8221; caption_location=&#8221;outside-image&#8221;][/vc_column][/vc_row][vc_row][vc_column][vc_empty_space][mk_fancy_title strip_tags=&#8221;true&#8221; tag_name=&#8221;span&#8221; size=&#8221;24&#8243; font_weight=&#8221;600&#8243; margin_top=&#8221;30&#8243; margin_bottom=&#8221;10&#8243; font_family=&#8221;none&#8221;]Pots, pans, and progress[/mk_fancy_title][vc_column_text css=&#8221;.vc_custom_1561464697724{margin-bottom: 0px !important;}&#8221;]Perhaps the best-known protests in Iceland are those that erupted following the banking collapse. Known as the Pots and Pans Revolution, the series of protests played a role in bringing down the ruling government. Thousands took to the streets in the largest protests the country had ever seen. For life-long activists like Stefán, it was a strange experience. “It was a bit like when the underground band that you’ve been a fan of for years suddenly becomes mainstream and everyone is listening to them.”</p>\n<p>While many leftist politicians were optimistic that the sudden momentum would lead to radical, structural changes, that didn’t turn out to be the case. “It’s not like everyone suddenly became communists after the banking collapse,” Stefán quips. “Many people went out to protest because they were really rich in 2007 and they just wanted their money back. You really have to have broader support to create social change.”</p>\n<p>Although the Pots and Pans Revolution may not have had the profound effect that is often attributed to it by foreign journalists, it nevertheless marked a shift in Icelandic protest culture. While previously, protests in Iceland were largely peopled by dedicated activists, suddenly those taking to the streets belonged to many diverse groups.[/vc_column_text][/vc_column][/vc_row]"""


def test_removing_tags():
    assert (
        remove_macro_tags(text) == """\n<img src="https://www.icelandreview.com/wp-content/uploads/2019/06/motmli011.jpg">\nPots, pans, and progressPerhaps the best-known protests in Iceland are those that erupted following the banking collapse. Known as the Pots and Pans Revolution, the series of protests played a role in bringing down the ruling government. Thousands took to the streets in the largest protests the country had ever seen. For life-long activists like Stefán, it was a strange experience. “It was a bit like when the underground band that you’ve been a fan of for years suddenly becomes mainstream and everyone is listening to them.”</p>\n<p>While many leftist politicians were optimistic that the sudden momentum would lead to radical, structural changes, that didn’t turn out to be the case. “It’s not like everyone suddenly became communists after the banking collapse,” Stefán quips. “Many people went out to protest because they were really rich in 2007 and they just wanted their money back. You really have to have broader support to create social change.”</p>\n<p>Although the Pots and Pans Revolution may not have had the profound effect that is often attributed to it by foreign journalists, it nevertheless marked a shift in Icelandic protest culture. While previously, protests in Iceland were largely peopled by dedicated activists, suddenly those taking to the streets belonged to many diverse groups."""
    )
